server:
  port: 2600
  tomcat:
    basedir: temp

spring:
  application:
    name: gateway #应用名称
  http: 
    multipart: 
      maxFileSize: 1024Mb
      maxRequestSize: 1024Mb
  cloud:
    consul:
      host: 192.168.159.131
      port: 8500
      discovery:
        register: true
        hostname: ${spring.cloud.client.ipAddress}
        serviceName: ${spring.application.name}
        preferIpAddress: true
        #healthCheckPath: /check  #自定义健康监测接口
        healthCheckInterval: 15s
        healthCheckCriticalTimeout: 60s
        tags: gate网关服务
        instanceId: ${spring.application.name}-${spring.cloud.consul.discovery.hostname}

zuul:
  retryable: false # 不允许重试
  host:
    max-per-route-connections: 60
    max-total-connections: 200
  routes:
    atm-server:
      path: /Api-Atm/**
      serviceId: atm-service
      sensitiveHeaders: "*"
    admin-server:
      path: /Api-Admin/**
      serviceId: admin-service
      sensitiveHeaders: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 45000  #Feign超时时间:45s

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 45000                    #路由api请求超时时间:45s

#自定义参数
appConfig:
  appName: atm-service-gateway
  appNameCn: atm网关服务
  
  tokenKey: 180808atm_dev   #Token加解密秘钥
  tokenDay: 7             #Token有效期，单位：天
  